### PR TITLE
Refactor for consistent and unambiguous auto-loading

### PR DESCRIPTION
**Pull request by qwertynik**
Thanks for building v3 of PHP SDK and incorporating modern PHP features for a better development experience 👍 

I am using this SDK is being used in a Laravel application. And `\com\zoho\crm\api\record\RecordOperations` is used to fetch records. When calling the class `\com\zoho\crm\api\record\GetRecordsParam` from within a `static` method it works. However, when calling it from a `non-static` method it fails. 
On inspection, it was found that in `vendor/zohocrm/php-sdk/src/com/zoho/crm/api/record/RecordOperations.php` multiple classes exist. This causes unexpected issues in auto-loading the classes.

On moving the classes out and creating individual classes, the `Class not found` error was resolved 🎉  This is NOT a breaking change because the namespace and the class names continue to remain the same 🔨 

**Note**  📓 
There are similar files in other folders as well that have multiple classes in the same file. To ensure consistent auto-loading, it is best to refactor those files such that there is only **one class per file**. 

Do let me know if you have any questions.

Looking forward to this PR being merged and downloading an update from Composer. 🛩️

### CODE REVIEW

**Comment by qwertynik** [comment]
@raja-7453 @Aswin97 
Do let me know if you have questions about this enhancement. 

Thanks!

**Comment by qwertynik** [comment]
This would also lead the SDK to be more compliant with the widely adopted and acclaimed PSR [standards](https://www.php-fig.org/psr/psr-1/#3-namespace-and-class-names)

**Comment by raja-k-7453** [comment]
@qwertynik Thanks for your contribution. We will incorporate the changes in the next major release.

**Comment by qwertynik** [comment]
@raja-7453 
Sure, good to know that this will be incorporated. Any ideas on when the next major release is scheduled?

**Comment by raja-k-7453** [comment]
@qwertynik The next release containing all the changes, will be available as soon as possible

**Comment by qwertynik** [comment]
@raja-7453 
That's great to know 🎆 

Since the existing SDK cannot be used due to auto-loading issues. We will have to wait for this upgrade before we could use this in our application. 🕦 

Would you be able to share any estimates on the same?

**Comment by raja-k-7453** [comment]
@qwertynik Please get in touch with support@zohocrm.com, for further updates. We will follow up on this request, over there.

Thanks!

**Comment by qwertynik** [comment]
Ok sure. Thanks!

**Pull request closed without merging**
